minio:
  url: https://play.min.io
  login: Q3AM3UQ867SPQQA43P2F
  password: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
